### ISSUE TITLE
Can't get NFS working

### ISSUE THREAD

**Issue by drakes00** [maier/vagrant-alpine#1]
Dear,

I am trying to get a sync folder working using NFS as you mentioned in the README.
If I run : 

```
$ vagrant plugin list
vagrant-alpine (0.1.1)
vagrant-exec (0.5.2)
vagrant-hostmanager (1.5.0)
vagrant-share (1.1.3, system)

$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "maier/alpine-3.1.3-x86_64"
  config.vm.network "private_network", ip: "192.168.200.10"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'maier/alpine-3.1.3-x86_64' is up to date...
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

The Vagrantfile is actually the one provided by the command :\

```
$ vagrant init maier/alpine-3.1.3-x86_64
```

in which I added the modifications you asked on the network and removed the comments to make it readable.

Maybe a dumb question, is it normal that the version of the plugin is 0.1.1 while current version on Atlas is 1.2.0?

Last thing maybe unrelated, if I disable nfs with : 

```
config.vm.synced_folder '.', '/vagrant', disabled: true
```

I am able to boot the VM and when I try to halt it, I get the message : 

```
$ vagrant halt
==> default: Attempting graceful shutdown of VM...
The SSH connection was unexpectedly closed by the remote end. This
usually indicates that SSH within the guest machine was unable to
properly start up. Please boot the VM in GUI mode to check whether
it is booting properly.
```

Could you tell me what I've done wrong?

Thanks a lot,
Regards,
Maxime

EDIT: Forgot to mention, I am running Ubuntu 14.04.2 LTS with Linux 3.13.0-55-generic and vagrant version is 1.7.3

**Comment by maier** [comment]
The first issue is because NFS is not configured on the host operating system. This is not part of the plugin itself - it is a feature of Vagrant to be able to mount via NFS. See the Vagrant documentation at (http://docs.vagrantup.com/v2/synced-folders/nfs.html). 

The vagrant alpine plugin is v0.1.1, the alpine virtualbox on atlas is 1.2.0 - they are two different things.

I will try to reproduce the second issue with SSH.

**Comment by drakes00** [comment]
Thanks for NFS, that was just me being dumb.
For SSH, it appears pretty randomly but often.
However it is not that much of a problem as you can launch the command
another time and it should be ok.

Regards,
Maxime

Le jeu. 16 juil. 2015 à 19:21, matt maier notifications@github.com a
écrit :
