### ISSUE TITLE
3.3.1 metadata is malformed?

### ISSUE THREAD

**Issue by timvisher** [maier/vagrant-alpine#12]
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'maier/alpine-3.3.1-x86_64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'maier/alpine-3.3.1-x86_64'
    default: URL: https://atlas.hashicorp.com/maier/alpine-3.3.1-x86_64
The metadata for the box was malformed. The exact error
is shown below. Please contact the maintainer of the box so
that this issue can be fixed.

Caught Encoding::CompatibilityError at '{"description":"Alpi': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
```

**Comment by maier** [comment]
What version of Vagrant? The metadata for the box is in accordance with the docs for the [Atlas post-processor](https://atlas.hashicorp.com/help/packer/artifacts/creating-vagrant-boxes) for Packer? I was unable to reproduce this when downloading/installing a new copy of the 3.3.1 box with vagrant v1.8.1. (this isn't related to the vagrant-alpine plugin directly)

**Comment by timvisher** [comment]
hmm… I thought it was for vagrant 1.8.1, vbox 5.0.16. I'll see if I can reproduce it again while paying attention. :)

**Comment by timvisher** [comment]
I'm not going to have any time to try to reproduce this now. Sorry for the noise. :(
