### ISSUE TITLE
alpine plugin fails on OSX when run with landrush

### ISSUE THREAD

**Issue by bertramn** [maier/vagrant-alpine#13]
I was trying the alpine box with landrush but get an error message that looks like a conflicting operation of the landrush module. 

```
==> haproxy: Waiting for machine to boot. This may take a few minutes...
    haproxy: SSH address: 127.0.0.1:2222
    haproxy: SSH username: vagrant
    haproxy: SSH auth method: private key
    haproxy: 
    haproxy: Vagrant insecure key detected. Vagrant will automatically replace
    haproxy: this with a newly generated keypair for better security.
    haproxy: 
    haproxy: Inserting generated public key within guest...
    haproxy: Removing insecure key from the guest if it's present...
    haproxy: Key inserted! Disconnecting and reconnecting using new SSH key...
Vagrant attempted to execute the capability 'iptables_installed'
on the detect guest OS 'alpine', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

I found a way to switch the landrush plugin off by adding `config.landrush.guest_redirect_dns = false` to the vagrant config but now I am getting the below error:

```
==> haproxy: Setting hostname...
==> haproxy: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -I

Stdout from the command:



Stderr from the command:

hostname: unrecognized option: I
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: hostname [OPTIONS] [HOSTNAME | -F FILE]

Get or set hostname or DNS domain name

    -s  Short
    -i  Addresses for the hostname
    -d  DNS domain name
    -f  Fully qualified domain name
    -F FILE Use FILE's content as hostname
```

Did anyone ever got this plugin to work with landrush on OSX?

Many thanks,
Niels

**Comment by maier** [comment]
I've never personally used landrush. But, looking through the code for the plugin, it seems to be a case of _landrush doesn't support Alpine Linux_ not _the vagrant-alpine plugin conflicting_ with landrush. Landrush has **iptables_installed** and **install_iptables** [capabilities in the code](https://github.com/vagrant-landrush/landrush/tree/master/lib/landrush/cap) for Debian and RedHat only. 

The reason for the second error is that Alpine Linux is based on [BusyBox](https://busybox.net/downloads/BusyBox.html) which provides (from busybox documentation):

> BusyBox combines tiny versions of many common UNIX utilities into a single small executable. It provides minimalist replacements for most of the utilities you usually find in GNU coreutils, util-linux, etc. The utilities in BusyBox generally have fewer options than their full-featured GNU cousins; however, the options that are included provide the expected functionality and behave very much like their GNU counterparts.

The linux `hostname -I` (_Display all network addresses of the host._) BusyBox equivalent seems to be `hostname -i` (_Addresses for the hostname_).

**Comment by bertramn** [comment]
Hi Matt, I will try the landrush folks and see if there is an option there to check the host type first before starting to apply network related configurations. Thanks Niels
