### ISSUE TITLE
Support Alpine 3.4 ?

### ISSUE THREAD

**Issue by William-Yeh** [maier/vagrant-alpine#14]
The Alpine Linux 3.4 has been released, and I've seen some other 3.4 boxes (such as https://atlas.hashicorp.com/adaptivdesign/boxes/alpine-3.4.0 ).  Would you plan to release a `maier/alpine-3.4-x86_64` as well?

**Comment by maier** [comment]
The Alpine Linux Vagrant plugin isn't tied to any version of Alpine. It should work with other alpine 3.4 boxes. I have built a 3.4 alpine box to test with so `vagrant init maier/alpine-3.4-x86_64` should now work if you prefer to use the boxes I build. The plugin did not require any updates, in my testing, to support alpine v3.4.
