### ISSUE TITLE
Vagrant error on alpine startup

### ISSUE THREAD

**Issue by COLABORATI** [maier/vagrant-alpine#17]
Not sure if this is the right place, however I would really like to use alpine iwth vagrant to save lots of diskspace. Unfortunately I get this error on `vagrant up` of `maier/alpine-3.4-x86_64`:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the command was:

mount: mounting vagrant on /vagrant failed: No such device
```

**Comment by maier** [comment]
Since Alpine does not support VirtualBox Guest Additions the line:

`config.vm.synced_folder '.', '/vagrant', disabled: true`

needs to be added to the Vagrantfile. (See [Vagrantfile.example](https://github.com/maier/vagrant-alpine/blob/master/Vagrantfile.example#L26) in repository).

**Comment by COLABORATI** [comment]
oh, yes, I now got it, sorry. 

Is there any open ticket regarding that virtualbox vs. alpine case? Seems like this should be easy for the virtualbox devs to solve, maybe we just have to ask for it?

**Comment by maier** [comment]
there was one, not sure if anyone has attempted to get virtualbox to move forward. https://www.virtualbox.org/ticket/9028
