### ISSUE TITLE
alpine 3.8 hostname doesn't accept --fqdn option

### ISSUE THREAD

**Issue by alainvanhoof** [maier/vagrant-alpine#30]
To set the hostname the command "hostname --fqdn" is used. The multi Binary busybox only accepts the option "-f" to set the hostname.

**Comment by maier** [comment]
interesting. the plugin uses `--fqdn` option to set the mailname and has worked in all previous versions. i'll look into 3.8 when it's released and update accordingly.

**Comment by alainvanhoof** [comment]
Nice.

Alpine released 3.8 An hour ago.

Cheers,
Alain.

**Comment by maier** [comment]
i just got the email and the downloads finally stopped returning 404. i have a copy now. it looks like they removed `--fqdn` support with this release, it was still functional in 3.7... 

seems like it will be an easy fix, switching to `-f` will hopefully work without needing to version detect for backwards compatibility.

**Comment by alainvanhoof** [comment]
Yeb, thats why I added the issue. I don’t know if “-f” works in 3.7 though.

**Comment by maier** [comment]
it's there but, i'm not sure in the older versions if `-f` returns the fqdn...need to test that before i release a patch.
