### ISSUE TITLE
Could you release a new version

### ISSUE THREAD

**Issue by BlackIkeEagle** [maier/vagrant-alpine#33]
Could you please release a new version so we can  use alpine 3.8 guests without manually having to change things in the vagrant-alpine plugin locally?

**Comment by maier** [comment]
What are you changing locally?

**Comment by maier** [comment]
Ah, ok. Published a new version with your PRs

**Comment by BlackIkeEagle** [comment]
Thank you so much :+1:  (This does not match the version of the tags I guess ;) )
