### ISSUE TITLE
Upstreaming into official Vagrant

### ISSUE THREAD

**Issue by timschumi** [maier/vagrant-alpine#34]
Hello @maier,

I have been working on an upstream-compatible version of your plugin [here](https://github.com/timschumi/vagrant/tree/patch/alpine-guest-plugin), which I ultimately plan to get ready for upstreaming into official vagrant.

Do you mind if I open a pull-request from that branch against upstream Vagrant? I'd mark it as WIP first, to track progress (since some parts might still need cleaning) and to get opinions on this from the Vagrant developers.

**Comment by maier** [comment]
@timschumi yeah, help yourself

**Comment by timschumi** [comment]
I now opened a pull-request against the official repository here (hashicorp/vagrant#10975). I listed some things that might still need discussion, I'd appreciate if you could give your opinion on that as well.

If the Pull Request ever gets ready to be merged, we'll have to find a way to handle [the CLA](https://www.hashicorp.com/cla), since the majority of the code is authored by you.

**Comment by timschumi** [comment]
The pull request has been merged, so I guess we can close this.
