### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by aldwinb** [maier/vagrant-alpine#4]
I ran into this problem today:

![screen shot 2015-11-03 at 5 32 54 pm](https://cloud.githubusercontent.com/assets/4484088/10923972/cacceeaa-8251-11e5-8eef-01cc879c0a6f.png)

Here's how my Vagrantfile looks like:

```
NODES = 1
MEMORY = 2048
CPUS = 2

config.vm.define "alpine-1" do |node|
  node.vm.box = "maier/alpine-3.1.3-x86_64"
  node.vm.synced_folder ".", "/vagrant", disabled: true

  # setup vm
  node.vm.provider :virtualbox do |v|
    v.name = "alpine-1"
    v.memory = MEMORY
    v.cpus = CPUS
    v.gui = true
  end
end
```

I tried multiple times, to no avail. I'm using OSX as my host. Have you ever run into something like this before?

**Comment by maier** [comment]
What versions of vagrant and virtualbox are you using? I'll see if I can reproduce and figure out what's going on.

**Comment by aldwinb** [comment]
Virtualbox: 5.0.8 r103449
Vagrant: 1.7.4

**Comment by aldwinb** [comment]
I think i figured out what's causing this: setting the number of Virtualbox CPUs to more than 1. I tested with setting it to 1 or don't set at all, and the box boots up fine. 

I thought that maybe the other VMs running in my machine are contributing to this, but I turned them off and I still get the error if I set the CPUs to more than 1.

**Comment by maier** [comment]
Ok, thanks for digging into that, I was out of town. I put up a new version of the alpine 3.1.3 vagrant box (v1.3.0) built with virtualbox 5.0.8 which comes up with `vb.cpus=2` for me when I test it. I can get the original alpine 3.1.3 vagrant box (v1.2.0) to come up sometimes with multiple CPUs but, it isn't consistent, it kernel panics as often as it comes up.

``` shell
alpine-313:~$ cat /proc/cpuinfo | grep -E "^(processor|vendor_id|model name)"
processor   : 0
vendor_id   : GenuineIntel
model name  : Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
processor   : 1
vendor_id   : GenuineIntel
model name  : Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
```

It will (sometimes) come up once, then kernel panic on `vagrant up` after a `vagrant halt`. The v1.3.0 vagrant box comes up reliably which leads me to think there is something related to differences between virtualbox v4 and v5 that is causing an issue with the vagrant box built against the previous version of virtualbox.

**Comment by aldwinb** [comment]
No problem. It was intermittent for me as well. At least we have a workaround for now. Thanks for looking at this.
