### ISSUE TITLE
alpine-3.2.3 not available but referenced from README

### ISSUE THREAD

**Issue by wsargent** [maier/vagrant-alpine#7]
> Alpine 3.2.3 box (built with VirtualBox v5) is available on (Atlas)[https://atlas.hashicorp.com/maier/boxes/alpine-3.2.3-x86_64] now.

The link seems not to work.

**Comment by maier** [comment]
The box image is now public. 

``` shell
curl -s -I "https://atlas.hashicorp.com/maier/boxes/alpine-3.2.3-x86_64" | grep -E "(HTTP|Status)"
HTTP/1.1 200 OK
Status: 200 OK
```
